name: setup-pesde
description: Installs the Pesde CLI along with Lune 

inputs:
  version:
    description: "Version of Pesde to install"
    required: false
  cache:
    description: "Whether or not to cache the Pesde install"
    default: "false"
    required: false
  token:
    description: "Token for publishing to the Pesde registry"
    required: false
  path:
    description: "The path to the pesde config file, typically used in monorepos"
    default: "."
    required: false

runs:
  using: composite
  steps:
    - name: Download releases
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        case ${{ runner.arch }} in
          "X86" | "X64") fileArch="x86_64" ;;
          "ARM" | "ARM64") fileArch="aarch64" ;;
        esac

        case ${{ runner.os }} in
          Linux) pattern="*-linux-$fileArch.zip" ;;
          macOS) pattern="*-macos-$fileArch.zip" ;;
          Windows) pattern="*-windows-$fileArch.zip" ;;
        esac

        gh release download ${{ inputs.version }} -R pesde-pkg/pesde -p "$pattern"
        gh release download -R lune-org/lune -p "$pattern"

    - name: Install releases
      shell: bash
      run: |
        for file in lune pesde; do
          mv ${file}*.zip ${file}.zip
          unzip ${file}.zip
          chmod +x ${file}
        done

        # Move Lune bin to HOME
        mkdir ~/.lune/bin
        mv lune ~/.lune/bin/lune

        ./pesde self-install

    - name: Add bins to PATH
      if: runner.os == 'Windows'
      shell: powershell
      run: |
        echo "$HOME/.pesde/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "$HOME/.lune/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Add bins to PATH
      if: runner.os != 'Windows'
      shell: bash
      run: |
        echo -e "$HOME/.pesde/bin\n$HOME/.lune/bin" >> $GITHUB_PATH

    - name: Remove artifacts
      shell: bash
      run: |
        rm pesde.zip lune.zip
        if ${{ runner.os == 'Windows' }}; then
          rm pesde.exe
        else
          rm pesde
        fi

    - name: Cache Pesde
      if: ${{ inputs.cache == true || inputs.cache == 'true' }}
      uses: actions/cache@v4
      with:
        path: |
          ~/.pesde
        key: ${{ runner.os }}-pesde-${{hashFiles(format('{0}/{1}', inputs.path, 'pesde.toml'))}}

    - name: Authenticate with Pesde
      if: inputs.token != ''
      shell: bash
      run: pesde auth login --token "${{ inputs.token }}"

branding:
  icon: box
  color: blue
