name: Action Test
on: 
  workflow_dispatch:
  push:
    paths:
      - '**.yml'
  pull_request:
    paths:
      - '**.yml'

defaults:
  run:
    shell: bash

jobs:
  test-cache:
    uses: ./.github/workflows/env.yml
    with:
      cache: 'true'
      pesde-version: 'v0.5.2'

  test:
    uses: ./.github/workflows/env.yml
    with:
      cache: 'false'
      pesde-version: 'v0.5.2'

